apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: elastic-search
data:
  elasticsearch.yml: |
    cluster.name: ${cluster.name}
    node.name: ${node.name}
    node.roles: ${node.roles}
    network.host: 0.0.0.0
    discovery.seed_hosts: ${discovery.seed_hosts}
    cluster.initial_master_nodes: ${cluster.initial_master_nodes}
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.jks
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.jks
    xpack.security.http.ssl.enabled: true
    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.jks
    xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.jks
