apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: es-tls-cert
  namespace: elastic-search
spec:
  secretName: es-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - es-client.elastic-search.svc.cluster.local
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: elastic-credentials
        key: password
    pkcs12:
      create: true
      passwordSecretRef:
        name: elastic-credentials
        key: password
