apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  namespace: elastic-search
spec:
  serviceName: es-master-headless
  replicas: 3
  selector:
    matchLabels:
      app: es-master
  template:
    metadata:
      labels:
        app: es-master
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - es-master
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: increase-vm-max-map-count
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: node.roles
          value: "master"
        - name: cluster.name
          value: "elasticsearch"
        - name: cluster.initial_master_nodes
          value: "es-master-0,es-master-1,es-master-2"
        - name: discovery.seed_hosts
          value: "es-master-headless"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xmx1g"
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: tls
          mountPath: /usr/share/elasticsearch/config/certs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: es-config
      - name: tls
        secret:
          secretName: es-tls-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 5Gi
