apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-snapshot-pvc
  namespace: elastic-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
