apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearch-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: elastic-search
roleRef:
  kind: ClusterRole
  name: elasticsearch-cluster-role
  apiGroup: rbac.authorization.k8s.io
