apiVersion: batch/v1
kind: Job
metadata:
  name: test-es-health
  namespace: elastic-search
spec:
  template:
    spec:
      containers:
      - name: test-es-health
        image: curlimages/curl:7.77.0
        command:
        - /bin/sh
        - -c
        - |
          sleep 30
          curl -s -k --user elastic:changeme https://es-client:9200/_cluster/health?wait_for_status=yellow&timeout=50s
      restartPolicy: Never
  backoffLimit: 4
